Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "vagrant-ubuntu"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "VUbuntu"
        vb.gui = true
        vb.memory = "2048"
        vb.customize [
            "modifyvm", :id,
            "--audio", "none",
            "--vram", "256",
            "--ioapic", "on",
            "--monitorcount", "1",
            "--graphicscontroller", "vmsvga"
        ]

    end

    config.vm.provision "shell", inline: <<-SHELL

        sudo apt-get -y update && apt-get -y install \
          curl \
          git \
          tree \
          htop \
          net-tools

        # Создание пользователя login:pass dev:dev
        sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/awkirin/awk-snippets/HEAD/add-dev-user.sh)"

    SHELL

end
