Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "vubuntu"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "vubuntu"
        vb.gui = false
        vb.memory = "2048"
        vb.customize [
            "modifyvm", :id,
            "--audio", "none",
            "--vram", "256",
            "--ioapic", "on",
            "--monitorcount", "1",
            "--graphicscontroller", "vmsvga"
        ]

    end

    config.vm.provision "shell", inline: <<-SHELL

        sudo apt-get -y update

        sudo apt-get -y install \
          curl \
          git \
          tree \
          htop \
          zsh \
          net-tools

        sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/awkirin/awk-snippets/HEAD/install-openssh-server.sh)"

        # add admin
        sudo USER_NAME="dev" USER_PASS="dev" /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/awkirin/awk-snippets/HEAD/add-admin-user.sh)"

    SHELL

end
