Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/jammy64"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "VUbuntu"
        vb.gui = true
        vb.memory = "2048"
        vb.customize [
            "modifyvm", :id,
            "--audio", "none",
            "--vram", "256",
            "--ioapic", "on",
            "--monitorcount", "1",
            "--graphicscontroller", "vmsvga",
            "--accelerate3d", "on"
        ]

    end

    config.vm.provision "shell", inline: <<-SHELL

        # Создание пользователя
        sudo useradd -m -s /bin/bash dev
        echo "dev:dev" | sudo chpasswd
        sudo usermod -aG sudo dev
        echo "dev ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/dev

        sudo apt-get -y update && apt-get -y install \
          curl \
          git \
          tree \
          htop \
          net-tools

    SHELL

end
